# GPT-2 pretraining setup
{
  # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
  # across the node boundaries )
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,

  # model settings
  "num_layers": 24,
  "mlp_expansion":
    [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
  "hidden_size": 1024,
  "num_attention_heads": 16,
  "seq_length": 256,
  "max_position_embeddings": 256,
  "norm": "layernorm",
  "pos_emb": "rotary",
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",

  # these should provide some speedup but takes a while to build, set to true if desired
  "scaled_upper_triang_masked_softmax_fusion": false,
  "bias_gelu_fusion": false,

  # init methods
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # optimizer settings
  "optimizer":
    {
      "type": "Adam",
      "params": { "lr": 0.0005, "betas": [0.9, 0.95], "eps": 1.0e-8 },
    },
  "min_lr": 0.00005,

  # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
  "zero_optimization":
    {
      "stage": 1,
      "allgather_partitions": True,
      "allgather_bucket_size": 500000000,
      "overlap_comm": True,
      "reduce_scatter": True,
      "reduce_bucket_size": 500000000,
      "contiguous_gradients": True,
    },
  # batch / data settings
  "train_batch_size": 32,
  "train_micro_batch_size_per_gpu": 8,
  "gradient_acc_step": 4,
  "data_impl": "mmap",

  # activation checkpointing
  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  # regularization
  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  # precision settings
  "fp16":
    {
      "fp16": true,
      "enabled": true,
      "loss_scale": 0,
      "loss_scale_window": 1000,
      "hysteresis": 2,
      "min_loss_scale": 1,
    },

  # misc. training settings
  "train_iters": 60000,
  "lr_decay_iters": 60000,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.02,
  "checkpoint_factor": 10000,
  "eval_interval": 1000,
  "eval_iters": 100,

  "data-path": "./data/books1/BookCorpusDataset_text_document",
  "use-wandb": True,
  "wandb-project": "variable-width",

  # logging
  "log_interval": 100,
  "steps_per_print": 100,
  "keep_last_n_checkpoints": 4,
  "wall_clock_breakdown": true,
}
